## 開発環境用上書設定

# Site settings
title: 開発環境
url: "" # 開発環境ではlocalhostを見る

# CSS
sass:
  style: :nested #開発環境ではネスト


## HTML圧縮（開発環境では非圧縮）
compress_html:
  clippings: none
  comments: []
  blanklines: true
